{{- if .Values.verticalPodAutoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: "{{ include "common.names.fullname" . }}-image-renderer"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       "{{ include "common.names.fullname" . }}-image-renderer"
  updatePolicy:
    updateMode: "Auto"
{{- end }}